services:
    _defaults:
        public: false
        autowire: true

    OxidEsales\MonduPayment\Core\Http\MonduClient:
        public: true

    OxidEsales\MonduPayment\Services\BuyerFeeCentsServiceInterface:
        class: OxidEsales\MonduPayment\Services\BuyerFeeCentsService
        public: true

    OxidEsales\MonduPayment\Event\SettingChangedSubscriber:
        tags: ['kernel.event_subscriber']

    request:
        public: true
        class: Symfony\Component\HttpFoundation\Request
        factory: ['Symfony\Component\HttpFoundation\Request', 'createFromGlobals']
